package:
  name: chemem
  version: "0.0.1"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - chemem = ChemEM.chemem:main
    - chemem.test = ChemEM.chemem:test

requirements:
  build:
    - python
    - pip
  host:
    - python
  run:
    - python
    - openff-toolkit
    - openff-toolkit-base
    - openff-toolkit-examples
    - spyrmsd
    - pdbfixer
    - pathos
    - pyfftw

    
about:
  home: https://chemem.topf-group.com/
  license: Copyright (c) 2023 - Topf Group and Leibniz Institute for Virology (LIV), Hamburg,  Germany. 
  summary: Software for fitting small molecules into Cryo-EM data.

files:
  - ChemEM/__tmp__/*
  - ChemEM/__tmp__/amino_acids/*
